#!/usr/bin/env bash
set -euo pipefail

# Install opencode-extras content into Claude Code's config directories.
#
# Skills and commands are symlinked directly - their SKILL.md format is
# compatible with Claude Code as-is.
#
# Agents require transformation: OpenCode uses a different frontmatter schema
# (temperature, mode, permissions map) than Claude Code (description only,
# with tools inherited). The script strips OpenCode-specific fields and writes
# the transformed files to ~/.claude/agents/. Generated files are always
# regenerated from source on each run.
#
# Generated agent files include a sentinel comment so the script can
# distinguish them from hand-crafted files it should not overwrite.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_CONFIG="${HOME}/.claude"

if [ ! -d "${CLAUDE_CONFIG}" ]; then
  echo "Error: ${CLAUDE_CONFIG} does not exist. Install Claude Code first."
  exit 1
fi

# ---------------------------------------------------------------------------
# Stale link cleanup
# ---------------------------------------------------------------------------

cleanup_stale_links() {
  local dest_dir="${CLAUDE_CONFIG}/$1"

  [ -d "${dest_dir}" ] || return 0

  for dest_file in "${dest_dir}"/*; do
    [ -L "${dest_file}" ] || continue
    local target
    target="$(readlink "${dest_file}")"
    [[ "${target}" == "${SCRIPT_DIR}"/* ]] || continue
    if [ ! -e "${dest_file}" ]; then
      rm "${dest_file}"
      echo "  removed stale link: ${1}/$(basename "${dest_file}")"
    fi
  done
}

# ---------------------------------------------------------------------------
# Symlink helpers (skills, commands)
# ---------------------------------------------------------------------------

link_files() {
  local src_dir="${SCRIPT_DIR}/$1"
  local dest_dir="${CLAUDE_CONFIG}/$1"

  if [ ! -d "${src_dir}" ]; then
    return
  fi

  mkdir -p "${dest_dir}"

  for src_file in "${src_dir}"/*; do
    [ -e "${src_file}" ] || continue
    local filename
    filename="$(basename "${src_file}")"
    local dest_file="${dest_dir}/${filename}"

    if [ -L "${dest_file}" ]; then
      local file_target
      file_target="$(readlink "${dest_file}")"
      if [[ "${file_target}" == "${src_file}" ]]; then
        echo "  already linked: ${1}/${filename}"
      else
        rm "${dest_file}"
        ln -s "${src_file}" "${dest_file}"
        echo "  relinked: ${1}/${filename}"
      fi
    elif [ -e "${dest_file}" ]; then
      echo "  skipping (file exists, not a symlink): ${1}/${filename}"
    else
      ln -s "${src_file}" "${dest_file}"
      echo "  linked: ${1}/${filename}"
    fi
  done
}

# ---------------------------------------------------------------------------
# Agent transformation
#
# Reads OpenCode agent frontmatter and writes a Claude Code-compatible agent.
# Claude Code agent frontmatter: name + description only. Omitting `tools`
# means the agent inherits all tools (maximally permissive). Unknown fields
# from OpenCode (temperature, mode, permissions) are dropped.
#
# The markdown body (everything after the closing ---) is preserved verbatim.
#
# A sentinel comment on the first line marks the file as generated by this
# script, so the stale-cleanup and overwrite-guard logic can distinguish
# generated files from hand-crafted files the user may have placed here.
# ---------------------------------------------------------------------------

SENTINEL="# Generated by install-claude.sh - do not edit manually"

transform_agent() {
  local src_file="$1"
  local dest_file="$2"
  local filename
  filename="$(basename "${src_file}")"

  # Extract description from frontmatter. Matches lines like:
  #   description: Some text here
  local description
  description="$(awk '/^---/{f++} f==1 && /^description:/{sub(/^description:[[:space:]]*/,""); print; exit}' "${src_file}")"

  if [ -z "${description}" ]; then
    echo "  warning: no description found in ${filename}, skipping"
    return
  fi

  # Extract the agent name (filename without .md extension)
  local agent_name="${filename%.md}"

  # Extract body: everything after the second --- delimiter
  local body
  body="$(awk '/^---/{f++; if(f==2){found=1; next}} found{print}' "${src_file}")"

  # Write the transformed file
  {
    echo "${SENTINEL}"
    echo "---"
    echo "name: ${agent_name}"
    printf 'description: "%s"\n' "${description//\"/\\\"}"
    echo "---"
    printf '%s\n' "${body}"
  } > "${dest_file}"

  echo "  wrote: agents/${filename}"
}

install_agents() {
  local src_dir="${SCRIPT_DIR}/agents"
  local dest_dir="${CLAUDE_CONFIG}/agents"

  if [ ! -d "${src_dir}" ]; then
    return
  fi

  mkdir -p "${dest_dir}"

  # Remove previously generated files that no longer have a source agent.
  # Only touches regular files bearing the sentinel comment (i.e. files this
  # script generated). Symlinks and hand-crafted files are left alone.
  for dest_file in "${dest_dir}"/*.md; do
    [ -e "${dest_file}" ] || continue
    [ -L "${dest_file}" ] && continue
    local first_line
    first_line="$(head -1 "${dest_file}")"
    [[ "${first_line}" == "${SENTINEL}" ]] || continue
    local filename
    filename="$(basename "${dest_file}")"
    local src_file="${src_dir}/${filename}"
    if [ ! -e "${src_file}" ]; then
      rm "${dest_file}"
      echo "  removed stale agent: agents/${filename}"
    fi
  done

  for src_file in "${src_dir}"/*.md; do
    [ -e "${src_file}" ] || continue
    local filename
    filename="$(basename "${src_file}")"
    local dest_file="${dest_dir}/${filename}"

    if [ -L "${dest_file}" ]; then
      echo "  skipping (symlink exists at destination): agents/${filename}"
      continue
    fi

    # Skip regular files not generated by this script (hand-crafted files).
    if [ -e "${dest_file}" ]; then
      local first_line
      first_line="$(head -1 "${dest_file}")"
      if [[ "${first_line}" != "${SENTINEL}" ]]; then
        echo "  skipping (file exists, not generated by this script): agents/${filename}"
        continue
      fi
    fi

    transform_agent "${src_file}" "${dest_file}"
  done
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

echo "Installing opencode-extras to Claude Code..."
cleanup_stale_links "commands"
cleanup_stale_links "skills"
cleanup_stale_links "agents"
link_files "commands"
link_files "skills"
install_agents
echo "Done."
