#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OPENCODE_CONFIG="${HOME}/.config/opencode"
CLAUDE_CONFIG="${HOME}/.claude"
PI_AGENT_DIR="${HOME}/.pi/agent"
PI_SKILLS_DIR="${PI_AGENT_DIR}/skills"
PI_PROMPTS_DIR="${PI_AGENT_DIR}/prompts"

CLAUDE_SENTINEL="# Generated by install.sh claude - do not edit manually"
CLAUDE_LEGACY_SENTINEL="# Generated by install-claude.sh - do not edit manually"
PI_SENTINEL="# Generated by install.sh pi - do not edit manually"

print_usage() {
  echo "Usage: ./install.sh <target>"
  echo "Supported targets:"
  echo "  opencode"
  echo "  claude"
  echo "  pi"
}

require_config_dir() {
  local config_dir="$1"
  local install_name="$2"

  if [ ! -d "${config_dir}" ]; then
    echo "Error: ${config_dir} does not exist. Install ${install_name} first."
    exit 1
  fi
}

cleanup_stale_links() {
  local config_dir="$1"
  local subdir="$2"
  local src_dir="${SCRIPT_DIR}/${subdir}"
  local dest_dir="${config_dir}/${subdir}"

  [ -d "${dest_dir}" ] || return 0

  for dest_file in "${dest_dir}"/*; do
    [ -L "${dest_file}" ] || continue

    local target
    target="$(readlink "${dest_file}")"
    [[ "${target}" == "${src_dir}"/* ]] || continue

    if [ ! -e "${dest_file}" ]; then
      rm "${dest_file}"
      echo "  removed stale link: ${subdir}/$(basename "${dest_file}")"
    fi
  done
}

link_single_file() {
  local src_rel_path="$1"
  local config_dir="$2"
  local dest_rel_path="$3"
  local src_file="${SCRIPT_DIR}/${src_rel_path}"
  local dest_file="${config_dir}/${dest_rel_path}"

  [ -e "${src_file}" ] || return 0

  if [ -L "${dest_file}" ]; then
    local target
    target="$(readlink "${dest_file}")"
    if [[ "${target}" == "${src_file}" ]]; then
      echo "  already linked: ${dest_rel_path}"
    else
      rm "${dest_file}"
      ln -s "${src_file}" "${dest_file}"
      echo "  relinked: ${dest_rel_path}"
    fi
  elif [ -e "${dest_file}" ]; then
    echo "  skipping (file exists, not a symlink): ${dest_rel_path}"
  else
    ln -s "${src_file}" "${dest_file}"
    echo "  linked: ${dest_rel_path}"
  fi
}

link_files() {
  local src_subdir="$1"
  local config_dir="$2"
  local dest_subdir="$3"
  local src_dir="${SCRIPT_DIR}/${src_subdir}"
  local dest_dir="${config_dir}/${dest_subdir}"

  if [ ! -d "${src_dir}" ]; then
    return 0
  fi

  mkdir -p "${dest_dir}"

  for src_file in "${src_dir}"/*; do
    [ -e "${src_file}" ] || continue

    local filename
    filename="$(basename "${src_file}")"
    local dest_file="${dest_dir}/${filename}"

    if [ -L "${dest_file}" ]; then
      local file_target
      file_target="$(readlink "${dest_file}")"
      if [[ "${file_target}" == "${src_file}" ]]; then
        echo "  already linked: ${dest_subdir}/${filename}"
      else
        rm "${dest_file}"
        ln -s "${src_file}" "${dest_file}"
        echo "  relinked: ${dest_subdir}/${filename}"
      fi
    elif [ -e "${dest_file}" ]; then
      echo "  skipping (file exists, not a symlink): ${dest_subdir}/${filename}"
    else
      ln -s "${src_file}" "${dest_file}"
      echo "  linked: ${dest_subdir}/${filename}"
    fi
  done
}

extract_description() {
  local src_file="$1"
  local description

  description="$(awk '/^---/{frontmatter_count++} frontmatter_count==1 && /^description:/{sub(/^description:[[:space:]]*/, ""); print; exit}' "${src_file}")"

  description="${description%\"}"
  description="${description#\"}"
  description="${description%\'}"
  description="${description#\'}"

  if [ -z "${description}" ]; then
    local filename
    filename="$(basename "${src_file}" .md)"
    description="${filename//-/ }"
  fi

  printf '%s\n' "${description}"
}

extract_markdown_body() {
  local src_file="$1"

  awk '/^---/{frontmatter_count++; if(frontmatter_count==2){in_body=1; next}} in_body{print}' "${src_file}"
}

transform_claude_agent() {
  local src_file="$1"
  local dest_file="$2"
  local filename
  filename="$(basename "${src_file}")"

  local description
  description="$(extract_description "${src_file}")"

  local agent_name="${filename%.md}"

  local body
  body="$(extract_markdown_body "${src_file}")"

  {
    echo "${CLAUDE_SENTINEL}"
    echo "---"
    echo "name: ${agent_name}"
    printf 'description: "%s"\n' "${description//\"/\\\"}"
    echo "---"
    printf '%s\n' "${body}"
  } > "${dest_file}"

  echo "  wrote: agents/${filename}"
}

transform_pi_prompt() {
  local src_file="$1"
  local dest_file="$2"
  local filename
  filename="$(basename "${src_file}")"

  local description
  description="$(extract_description "${src_file}")"

  local body
  body="$(extract_markdown_body "${src_file}")"

  {
    echo "${PI_SENTINEL}"
    echo "---"
    printf 'description: "%s"\n' "${description//\"/\\\"}"
    echo "---"
    printf '%s\n' "${body}"
  } > "${dest_file}"

  echo "  wrote: prompts/${filename}"
}

matches_non_empty_sentinel() {
  local first_line="$1"
  local sentinel="$2"

  [ -n "${sentinel}" ] && [[ "${first_line}" == "${sentinel}" ]]
}

is_generated_file() {
  local first_line="$1"
  local sentinel="$2"
  local legacy_sentinel="$3"

  if matches_non_empty_sentinel "${first_line}" "${sentinel}"; then
    return 0
  fi

  if matches_non_empty_sentinel "${first_line}" "${legacy_sentinel}"; then
    return 0
  fi

  return 1
}

cleanup_stale_generated_files() {
  local src_dir="$1"
  local dest_dir="$2"
  local sentinel="$3"
  local legacy_sentinel="$4"
  local label="$5"

  for dest_file in "${dest_dir}"/*.md; do
    [ -e "${dest_file}" ] || continue
    [ -L "${dest_file}" ] && continue

    local first_line
    IFS= read -r first_line < "${dest_file}" || true
    if ! is_generated_file "${first_line}" "${sentinel}" "${legacy_sentinel}"; then
      continue
    fi

    local filename
    filename="$(basename "${dest_file}")"
    local src_file="${src_dir}/${filename}"
    if [ ! -e "${src_file}" ]; then
      rm "${dest_file}"
      echo "  removed stale ${label}: ${label}s/${filename}"
    fi
  done
}

install_generated_markdown_files() {
  local src_dir="$1"
  local dest_dir="$2"
  local sentinel="$3"
  local legacy_sentinel="$4"
  local label="$5"
  local transform_function="$6"

  if [ ! -d "${src_dir}" ]; then
    return 0
  fi

  mkdir -p "${dest_dir}"
  cleanup_stale_generated_files "${src_dir}" "${dest_dir}" "${sentinel}" "${legacy_sentinel}" "${label}"

  for src_file in "${src_dir}"/*.md; do
    [ -e "${src_file}" ] || continue

    local filename
    filename="$(basename "${src_file}")"
    local dest_file="${dest_dir}/${filename}"

    if [ -L "${dest_file}" ]; then
      echo "  skipping (symlink exists at destination): ${label}s/${filename}"
      continue
    fi

    if [ -e "${dest_file}" ]; then
      local first_line
      IFS= read -r first_line < "${dest_file}" || true
      if ! is_generated_file "${first_line}" "${sentinel}" "${legacy_sentinel}"; then
        echo "  skipping (file exists, not generated by this script): ${label}s/${filename}"
        continue
      fi
    fi

    "${transform_function}" "${src_file}" "${dest_file}"
  done
}

install_opencode() {
  require_config_dir "${OPENCODE_CONFIG}" "opencode"

  echo "Installing opencode-extras to OpenCode..."
  cleanup_stale_links "${OPENCODE_CONFIG}" "commands"
  cleanup_stale_links "${OPENCODE_CONFIG}" "agents"
  cleanup_stale_links "${OPENCODE_CONFIG}" "skills"
  link_files "commands" "${OPENCODE_CONFIG}" "commands"
  link_files "agents" "${OPENCODE_CONFIG}" "agents"
  link_files "skills" "${OPENCODE_CONFIG}" "skills"
  link_single_file "opencode.json" "${OPENCODE_CONFIG}" "opencode.json"
  echo "Done."
}

install_claude() {
  require_config_dir "${CLAUDE_CONFIG}" "Claude Code"

  echo "Installing opencode-extras to Claude Code..."
  cleanup_stale_links "${CLAUDE_CONFIG}" "commands"
  cleanup_stale_links "${CLAUDE_CONFIG}" "skills"
  cleanup_stale_links "${CLAUDE_CONFIG}" "agents"
  link_files "commands" "${CLAUDE_CONFIG}" "commands"
  link_files "skills" "${CLAUDE_CONFIG}" "skills"
  install_generated_markdown_files "${SCRIPT_DIR}/agents" "${CLAUDE_CONFIG}/agents" "${CLAUDE_SENTINEL}" "${CLAUDE_LEGACY_SENTINEL}" "agent" "transform_claude_agent"
  echo "Done."
}

install_pi() {
  echo "Installing opencode-extras to Pi..."
  mkdir -p "${PI_AGENT_DIR}" "${PI_SKILLS_DIR}" "${PI_PROMPTS_DIR}"
  cleanup_stale_links "${PI_AGENT_DIR}" "skills"
  link_files "skills" "${PI_AGENT_DIR}" "skills"
  echo "  note: commands/ has no direct Pi mapping; skipping commands install"
  install_generated_markdown_files "${SCRIPT_DIR}/agents" "${PI_PROMPTS_DIR}" "${PI_SENTINEL}" "" "prompt" "transform_pi_prompt"
  echo "Done."
}

main() {
  if [ "$#" -ne 1 ]; then
    print_usage
    exit 1
  fi

  local target="$1"

  case "${target}" in
    opencode)
      install_opencode
      ;;
    claude)
      install_claude
      ;;
    pi)
      install_pi
      ;;
    *)
      print_usage
      exit 1
      ;;
  esac
}

main "$@"
